### ISSUE TITLE
Reunião 30/03/2021

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSibling/BigSibling#159]
# Reunião semanal 

- **Data:** 30 de março de 2021
- **Ata da reunião anterior**: ...
- **Participantes**:
  - Nome 1
  - Nome 2

### Acompanhamento das ações pendentes da última reunião

- [x] Treinamento de mentoras #157 
- [ ] Coletar minibio, nome e foto de mentoras #158 
- [x] Criar e divulgar inscrição da BOSS Maratona #156 
- [x] Criar roteiro para vídeo da final #147
- [ ] Escolher gerenciador de senhas #152 

### Itens a serem debatidos

- [x] Ideia para o vídeo da final **V1: vídeo depoimento, se der, v2: vídeo narrado em cima do slide**
- [x] Reunião para gravação do vídeo pra enviar **sexta, dia 2, das 15 às 18 no zoom** 
- [x]  Texto descritivo de imagens **Sempre descrever o conteúdo da imagem na issue e lembrar de adicionar nas redes**
- [x]  Mensagem convidando as mentoras para o treinamento e convite na agenda @ludimila 
- [x] Separar grupos: mentora, organização, talk like a boss, social media
- [x] Resposta para o email da gnome
  - [x] Vídeo
  - [x] Showcase
  - [x] Social media
- [x] Texto para a Bots Brasil divulgar a gente  @RochaCarla 

### Tarefas criadas

- [ ] Roteiro para o vídeo (@ludimila )
- [ ] Convite para o treinamento (@belaaiza )
- [ ] Texto para a Bots Brasil divulgar a gente  @RochaCarla 

Link do jitsi para treinamento https://meet.jit.si/big-open-source-sister

@BOSS-BigOpenSourceSister/mentoras
