### ISSUE TITLE
Reunião 06/04/2021

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#163]
# Reunião semanal

- **Data:** 06 de Abril de 2021
- **Ata da reunião anterior**: [Link](link)
- **Participantes**:
  - Nome 1
  - Nome 2

### Acompanhamento das ações pendentes da última reunião

- [ ]  Coletar minibio, nome e foto de mentoras #158
- [ ]  Escolher gerenciador de senhas #152
- [ ]  Texto para a Bots Brasil #162 
- [ ] Alinhar expectativas quanto a redes sociais

### Itens a serem debatidos

- [x]  Seleção de participantes BOSS Maratona **Essa foi a decisão final**
- [ ]  Programaria também mandou outro e-mail, vou pedir pra elas divulgarem o forms hoje!
- [ ]  Tópico 1: Essa é a ideia do tópico. **Essa foi a decisão final**
- [ ]  Tópico 1: Essa é a ideia do tópico. **Essa foi a decisão final**

### Tarefas criadas

- [ ] Pedir para pessoas mentoras descreverem suas fotos colocadas na issue #158
- [ ] Enviar E-mail Selecionadas BOSS Maratona #164
- [ ] Falar com Canela para divulgar o forms de participantes no EducaTRANSforma. @BrunaNayara 
- [ ] Treinamento de Mentoras - Semana 2 #157
- [ ] Sync com ICTL para resgatarmos o prêmio GNOME #166

@BOSS-BigOpenSourceSister/mentoras

**Comment by Joranhezon** [comment]
Notei que o número de pessoas trans se inscrevendo para participar está bem baixo, seria legal pensarmos em uma maneira para divulgar pra chegar nessas pessoas.

Programaria também me mandou outro e-mail, vou pedir pra elas divulgarem o forms hoje!
