### ISSUE TITLE
Reunião 13/04/2021

### ISSUE THREAD

**Issue by naiieandrade** [BOSS-BigOpenSourceSibling/BigSibling#168]
# Reunião semanal 

- **Data:** 13 de Abril de 2021
- **Ata da reunião anterior**: [Link](link)
- **Participantes**:
  - Nome 1
  - Nome 2

### Acompanhamento das ações pendentes da última reunião

- [X] Escolher gerenciador de senha #152 
- [X] Alterar nome do instagram para @open.source.sibling
- [X] Coletar minibio, nome e foto de mentoras #158
- [X] Texto para a Bots Brasil #162 
- [X] Pedir para pessoas mentoras descreverem suas fotos colocadas na issue #158
- [X] Enviar E-mail Selecionadas BOSS Maratona #164
- [X] Falar com Canela para divulgar o forms de participantes no EducaTRANSforma. 
- [X] Treinamento de Mentoras - Semana 2 #157
- [X] Sync com ICTL para resgatarmos o prêmio GNOME #166
- [X] Contato do educa transforma
- [X] lembra as pessoas sobre divulgar a programaria pls? no insta e linkedin (twitter tá feito)

### Itens a serem debatidos

- [X] Gerenciador de senha testado no gratuito e upgrade se for o caso (https://github.com/BOSS-BigOpenSourceSibling/BigSibling/issues/152#issuecomment-819079931)
- [X]  Seremos parceiros do ICTL **E recebermos a última (se der certo, todas) parcela do prêmio aqui**
- [ ]  [Google for Nonprofits](https://www.google.com/intl/pt-BR/nonprofits/offerings/workspace/#!#workspace-pricing)
- [X]  Vale a pena pensarmos em uma alternativa FOSS para o slack? **Hoje não, mas pro futuro, sim. Olhar mattermost**
- [X]  @BrunaNayara disse: Preciso atualizar o texto da arte de divulgação
- [X]  Definir critérios para seleção de participantes (recortes de gênero, região)

### Tarefas criadas

- [ ] Falar com a Shai do Educa Transforma @belaaiza 
- [ ] Pra próxima semana tem que estruturar direitinho a semana 1 das litlle siblings
- [ ] Definição dos critérios para seleção de participantes @emmenezes 

- [ ] Divulgar programaria no insta e twitter (@naiieandrade e @ludimila) 

@BOSS-BigOpenSourceSister/mentoras
