### ISSUE TITLE
Reunião 27/04/2021

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#177]
_Edite esse template antes da reunião com as pautas a serem discutidas. Incentive sugestões de pauta. Formalize as decisões das reuniões aqui. Não se esqueça de fechar a issue após a reunião e a revisão da ata._

# Reunião semanal

- **Data:** 27.04.2021.
- **Ata da reunião anterior**: [Link]link)

### Acompanhamento das ações pendentes da última reunião

- [x] Tag #BOSSResponde (sugestão) no twitter pra tirar dúvidas (respostas em vídeo, tweets e mentoradas)
- [ ] Criar regras de contribuição no repositório (papéis e poderes) #173 
- [ ] Definição de papéis que a gente precisa dentro da organização (comunicação email/redes, apresentação e divulgação, captação de recursos e parcerias) #171 
- [x] Encontrar alguém para gerenciamento (engajamento/ajuda/ir atrás além das reuniões de acompanhamento semanal) de pessoas mentoras (  @emmenezes  e @belaaiza )
- [x] Mandar msg pras mentoras entrarem no slack

### Itens a serem debatidos

- [ ]  Formulário Pessoas Mentoradas: Quem foi Selecionado? Como vamos mandar os e-mails?
- [ ]  Formulário Pessoas Mentoradas: Quais são os possíveis resultados? (@emmenezes)

### Tarefas criadas

- [ ] Selecionar Pessoas Mentoradas(Bruna, Duda, Iza, Marina) #179 ;
- [ ] Criar um Survey para pessoas mentoras e mentoradas selecionadas sobre uso de imagem(Nai) #180 ;
- [ ] Enviar mensagem no telegram com link do slack para Pessoas Mentoras que não entraram ainda(Joranhezon) #181 ;
- [ ] Mandar e-mails referente ao resultado do formulário de mentoradas(Claris e Carla)(Essa semana) #182;
- [ ] Fazer um mini-manual para ser enviado para pessoas mentoradas(Bruna e Carla) #183
- [ ] Fazer maillist da BOSS(Trazer na próxima semana) #184
- [ ]  Criar regras de contribuição no repositório (papéis e poderes) #173
- [ ] Definição de papéis que a gente precisa dentro da organização (comunicação email/redes, apresentação e divulgação, captação de recursos e parcerias) #171

### Pontos levantados para a próxima reunião
- [ ] Ponto 1
- [ ] Ponto 2

_Lembre-se de fechar a issue._

@BOSS-BigOpenSourceSister/organização
