### ISSUE TITLE
Reunião 04/05/2021

### ISSUE THREAD

**Issue by naiieandrade** [BOSS-BigOpenSourceSibling/BigSibling#188]
_Edite esse template antes da reunião com as pautas a serem discutidas. Incentive sugestões de pauta. Formalize as decisões das reuniões aqui. Não se esqueça de fechar a issue após a reunião e a revisão da ata._

# Reunião semanal

- **Data:** 04.05.2021.
- **Ata da reunião anterior**: [https://github.com/BOSS-BigOpenSourceSibling/BigSibling/issues/177](https://github.com/BOSS-BigOpenSourceSibling/BigSibling/issues/177)

### Acompanhamento das ações pendentes da última reunião

- [x] Selecionar Pessoas Mentoradas(Bruna, Duda, Iza, Marina) #179 ;
- [x] Criar um Survey para pessoas mentoras e mentoradas selecionadas sobre uso de imagem(Nai) #180 ;
- [ ] Enviar mensagem no telegram com link do slack para Pessoas Mentoras que não entraram ainda(Joranhezon) #181 ;
- [x] Mandar e-mails referente ao resultado do formulário de mentoradas(Claris e Carla)(Essa semana) #182;
- [ ] Fazer um mini-manual para ser enviado para todo mundo (organização/participantes)(Bruna e Carla) #183
- [ ] Criar regras de contribuição no repositório (papéis e poderes) #173
- [ ] Definição de papéis que a gente precisa dentro da organização (comunicação email/redes, apresentação e divulgação, captação de recursos e parcerias) #171

### Itens a serem debatidos

- [ ]  Tópico 1: Essa é a ideia do tópico.

### Tarefas criadas

- [ ] Fazer maillist da BOSS(todos que demonstraram interesse na BOSS)(Ludi) #184
- [ ] [10/05/21] Primeira semana das participantes (Carla e Marina)
- [ ] Criar evento no Calendário para enviar no email (Clarissa e Carla)
- [ ] [17/05/21] Segunda semana das participantes - GIT (Ludi)
- [ ] [24/05/21] Terceira semana das participantes - Gitflow (Definir responsável)
- [ ] Acompanhar/orientar pessoas mentoras (Iza e Duda)
- [ ] Selecionar os pares de pessoas mentoras e mentorandas (Bruna)
- [ ] Pessoas para Redes sociais (Iza)
- [ ] Formulário pra chamada de pessoas para as Redes sociais (Naiara)
- [ ] Boas práticas com o uso do email da organização (Bruna e Naiara)
- [x] Organizar o email (Bruna)

### Pontos levantados para a próxima reunião
- [ ] Ponto 1
- [ ] Ponto 2

_Lembre-se de fechar a issue._

@BOSS-BigOpenSourceSister/organização
