### ISSUE TITLE
Reunião 18/05/2021

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSibling/BigSibling#191]
# Reunião semanal

- **Data:** 18.05.2021.
- **Ata da reunião anterior**: [Link]link)

### Acompanhamento das ações pendentes da última reunião

- [ ] Fazer um mini-manual para ser enviado para todo mundo (organização/participantes)(Bruna e Carla) #183
- [ ] Criar regras de contribuição no repositório (papéis e poderes) #173 @ludimila 
- [ ] Definição de papéis que a gente precisa dentro da organização (comunicação email/redes, apresentação e divulgação, captação de recursos e parcerias) #171
- [ ] [24/05/21] Terceira semana das participantes - Gitflow (Bruna)
- [ ] [31/05/21] Terceira semana das participantes - Software livre (Carla e Clarissa)
- [X] Selecionar os pares de pessoas mentoras e mentorandas (Bruna)
- [ ] Formulário pra chamada de pessoas para as Redes sociais (Naiara)
- [ ] Boas práticas com o uso do email da organização (Bruna e Naiara)
- [ ] Definir reunião quinzenal com as mentoras (Iza e Duda)

### Itens a serem debatidos

- [ ]  Talk like a boss semana do dia 31/05 (Clarissa)
- [x]  Falar com as pessoas mentoras sobreo contato com as mentoradas (Iza e Duda)
- [ ] Dinheiros: Vamos tentar receber pela Clarissa
- [ ] Atividade de pareamento na quarta: Ensinar o que é pareamento, abrir sala no jitsi, pareamento remoto e tarefa do readme.

### Tarefas criadas

- [ ] Tarefa que criamos agora (@ da pessoa responsável)
- [ ] Tarefa que criamos agora (@ da pessoa responsável)

### Pontos levantados para a próxima reunião
- [ ] Ponto 1
- [ ] Ponto 2

_Lembre-se de fechar a issue._

@BOSS-BigOpenSourceSister/organização

**Comment by belaaiza** [comment]
Juliana Fajardini OK
Marina Joranhezon OK
Lais Petra OK
Lucas Severo (AGUARDANDO CONFIRMACAO DA BRUNA - nova little sibling -)
Kamilla Crozara OK
Rafaella Junqueira OK
Geovana Ramos (AGUARDANDO CONFIRMACAO DA BEATRIZ - nova little sibling -)
Bárbara Domingues (AGUARDANDO CONFIRMACAO DA DANY - nova little sibling -)
Vítor Menezes OK
Andressa Valadares OK
Débora Atanes OK
Dessa Freires OK
Naiara Andrade OK
Keline Dantas OK
