### ISSUE TITLE
Reunião 25/05/2021

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#194]
_Edite esse template antes da reunião com as pautas a serem discutidas. Incentive sugestões de pauta. Formalize as decisões das reuniões aqui. Não se esqueça de fechar a issue após a reunião e a revisão da ata._

# Reunião semanal

- **Data:** 25.05.2021.
- **Ata da reunião anterior**: #191 

### Acompanhamento das ações pendentes da última reunião

- [ ] Fazer um mini-manual para ser enviado para todo mundo (organização/participantes)(Bruna e Carla) #183
- [ ] Criar regras de contribuição no repositório (papéis e poderes) #173 @ludimila 
- [ ] Definição de papéis que a gente precisa dentro da organização (comunicação email/redes, apresentação e divulgação, captação de recursos e parcerias) #171
- [x] [31/05/21] Quarta semana das participantes - Software livre (Carla e Clarissa)
- [ ] Formulário pra chamada de pessoas para as Redes sociais (Naiara)
- [ ] Boas práticas com o uso do email da organização (Bruna e Naiara)
- [x] Definir reunião quinzenal com as mentoras (Iza e Duda)

### Itens a serem debatidos

- [ ]  Tópico 1: Essa é a ideia do tópico.
- [ ]  Tópico 1: Essa é a ideia do tópico.

### Tarefas criadas

- [ ] Tarefa que criamos agora (@ da pessoa responsável)
- [ ] Tarefa que criamos agora (@ da pessoa responsável)

### Pontos levantados para a próxima reunião
- [ ] Ponto 1
- [ ] Ponto 2

_Lembre-se de fechar a issue._

@BOSS-BigOpenSourceSister/organização

**Comment by Joranhezon** [comment]
Na semana quatro sobre Software Livre:
- Abrir comunidades reais e o guia de contribuicao;
- Trazer comunidades em pt br

@clarissalimab @RochaCarla

**Comment by RochaCarla** [comment]
Fazer issue checklist dos workshops
- Lembrar de colocar dicas de acessibilidade
