### ISSUE TITLE
Reunião 01-06

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSibling/BigSibling#196]
# Reunião semanal

- **Data:** 01.06.2021.
- **Ata da reunião anterior**: #194 

### Acompanhamento das ações pendentes da última reunião
- [ ] Fazer um mini-manual para ser enviado para todo mundo (organização/participantes)(Bruna e Carla) #183
- [ ] Definição de papéis que a gente precisa dentro da organização (comunicação email/redes, apresentação e divulgação, captação de recursos e parcerias) #171
- [ ] Formulário pra chamada de pessoas para as Redes sociais (Naiara)
- [ ] Boas práticas com o uso do email da organização (Lud)
- [ ] Dinheiro

### Itens a serem debatidos

- [ ]  Tópico 1: Essa é a ideia do tópico.
- [ ]  Tópico 1: Essa é a ideia do tópico.

### Tarefas criadas

- [ ] Melhorar checklist do Workshop / Alterar template da issue de novo conteúdo (Carla) 
- [ ] Tarefa que criamos agora (@ da pessoa responsável)
- [ ] 07-06 - visão geral chatbot - (bruna)
- [ ] 14-06 - Arquitetura boilerplate (Alessandra?)
- [ ] Talk like a boss - software livre tech lead - clarissa - 17-06 #197
- [ ] Talk like a boss - Entrevista técnica - Lud - 30-06 #198

### Pontos levantados para a próxima reunião
- [ ] Ponto 1
- [ ] Ponto 2

_Lembre-se de fechar a issue._

@BOSS-BigOpenSourceSister/organização
