### ISSUE TITLE
Reunião 08/06

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#199]
_Edite esse template antes da reunião com as pautas a serem discutidas. Incentive sugestões de pauta. Formalize as decisões das reuniões aqui. Não se esqueça de fechar a issue após a reunião e a revisão da ata._

# Reunião semanal

- **Data:** 08.06.2021.
- **Ata da reunião anterior**: #196 
### Acompanhamento das ações pendentes da última reunião

- [x] Melhorar checklist do Workshop / Alterar template da issue de novo conteúdo (Carla) 
- [x] 07-06 - visão geral chatbot - (bruna)
- [x] 14-06 - Arquitetura boilerplate (Bruna)
- [ ] Talk like a boss - software livre tech lead - clarissa - 17-06 #197
- [ ] Talk like a boss - Entrevista técnica - Lud - 30-06 #198

### Itens a serem debatidos

- [x]  Próxima Talk Like a Boss, já que a da Ana foi postergada. ( @Joranhezon )
- [x] Tarefas semanais muito grandes ou complicadas, causando desespero e pavor geral hahaha (bruna)

### Tarefas criadas
- Mandar e-mail para possíveis patrocinadores ( @ludimila ) #200 
- Criar plano de patrocinio #201 

### Pontos levantados para a próxima reunião
- [ ] Vamos trocar para o kumospace para sempre nos pareamentos?
- [ ] Talk like a boss - software livre tech lead - clarissa - 17-06 #197
- [ ] Talk like a boss - Entrevista técnica - Lud - 30-06 #198
- [ ] 14-06 - Arquitetura boilerplate(Docker também) (Bruna)
- [ ] 21-06 Aula de Actions ( Falar muiiito de Python) ( @Joranhezon e @RafaellaJunqueira   )

_Lembre-se de fechar a issue._

@BOSS-BigOpenSourceSister/organização
