### ISSUE TITLE
Reunião 06/07/21

### ISSUE THREAD

**Issue by RafaellaJunqueira** [BOSS-BigOpenSourceSibling/BigSibling#209]
_Edite esse template antes da reunião com as pautas a serem discutidas. Incentive sugestões de pauta. Formalize as decisões das reuniões aqui. Não se esqueça de fechar a issue após a reunião e a revisão da ata._

# Reunião semanal

- **Data:** 06.07.2021.
- **Ata da reunião anterior**: [Reunião 29/06/21](https://github.com/BOSS-BigOpenSourceSibling/BigSibling/issues/207)

### Acompanhamento das ações pendentes da última reunião

- [x] Como tá receber o prêmio (@clarissalimab) -> Claris não ta mais com a tarefa ([Comentário](https://github.com/BOSS-BigOpenSourceSibling/BigSibling/issues/207#issuecomment-871480292))
- [x] **08/07** -> Finalizar roteiro da Talk Like a BOSS "Liderança Técnica..." (#197) (@clarissalimab @ludimila)
- [x] **Próximo conteúdo: 12/07** -> Contribuição nas issues do Bot da BOSS (@BrunaNayara @RafaellaJunqueira )
- [x] **Próximo conteúdo: 19/07** -> Contribuição nas issues do Bot da BOSS again
- [ ] Definir como será a chamada para a contribuição e cobrar a Bruna por isso Definir como será a chamada para a contribuição #208

### Itens a serem debatidos

- [x] Arranjar outras comunidades para contribuição tipo HacktoberFest (além da do Kanela e do Terceiro) -> Responsáveis após votos unânimes: @clarissalimab @dehatanes @RochaCarla
- [x] Datas de apresentação de outras comunidades: 26/07 e 02/08

### Tarefas criadas

- [ ] Abrir issues para as participantes contribuírem no Bot-da-boss
- [ ] Criar template da reunião de acompanhamento da mentoria @emmenezes @belaaiza 

### Pontos levantados para a próxima reunião
- Definir responsável pela segunda feira de contribuição ( 19/07 )
- Uso do Slack (está sendo útil?)

_Lembre-se de fechar a issue._

@BOSS-BigOpenSourceSibling/organizacao

**Comment by dehatanes** [comment]
O que que é isso que eu votei aí? 👀  hahahahaha
![image](https://user-images.githubusercontent.com/17599203/124671790-69fe6700-de8c-11eb-88c4-b5b9dc89a9b3.png)

**Comment by RafaellaJunqueira** [comment]
Os votos unânimes foram para atribuir a você a responsabilidade de achar novas comunidades pro povo contribuir ;)

**Comment by dehatanes** [comment]
> Os votos unânimes foram para atribuir a você a responsabilidade de achar novas comunidades pro povo contribuir ;)

🔝  hahahahahaha
